In [205]:
import pandas as pd
import numpy as np

In [206]:
df=pd.read_excel(r"C:\Users\Dell\Desktop\CricketdataA.xlsx")
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1
6,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
7,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4
8,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27
9,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
10,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,-,-,15,19,6,258+,2
11,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
13,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,-,-,15,14,1,107+,11
16,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7
17,SPD Smith (AUS),2010-2026,123,220,28,10763,239,56.05,19966,53.9,37,44,11,1172,67
18,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
19,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2
20,HC Brook (ENG),2022-2026,35,60,2,3178,317,54.79,3660,86.83,10,15,4,339,52
21,KS Williamson (NZ),2010-2025,108,192,19,9461,251,54.68,18198,51.98,33,38,11,1056,28
22,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1
23,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
24,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16
25,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6
26,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26
38,JE Root (ENG),2012-2026,163,298,25,13943,262,51.07,24242,57.51,41,66,15,1492,46
39,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
40,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.1,30,29,14,1049,82
41,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64
42,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28

In [147]:
#rename multiple
df=df.rename(columns={'NO':'Not_Outs','HS':'Highest_Inns_score','BF':'Ball_face','SR':'Batting_strike_rate'})

In [148]:
df.head()

,Player,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11

In [149]:
#check nulls
df.isnull().any()
#nan is not shown it only shows real null so better using unique data

Player                 False
Span                   False
Mat                    False
Inns                   False
Not_Outs               False
Runs                   False
Highest_Inns_score     False
Ave                    False
Ball_face              False
Batting_strike_rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

In [150]:
df = df.replace(['NA', 'N/A', 'null', '-'], np.nan)
df

C:\Users\Dell\AppData\Local\Temp\ipykernel_20052\3029729789.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(['NA', 'N/A', 'null', '-'], np.nan)

,Player,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1
6,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6
7,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4
8,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27
9,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
10,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258+,2
11,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
13,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107+,11
16,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7
17,SPD Smith (AUS),2010-2026,123,220,28,10763,239,56.05,19966,53.90,37,44,11,1172,67
18,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
19,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2
20,HC Brook (ENG),2022-2026,35,60,2,3178,317,54.79,3660,86.83,10,15,4,339,52
21,KS Williamson (NZ),2010-2025,108,192,19,9461,251,54.68,18198,51.98,33,38,11,1056,28
22,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1
23,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6
24,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16
25,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6
26,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26
38,JE Root (ENG),2012-2026,163,298,25,13943,262,51.07,24242,57.51,41,66,15,1492,46
39,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20
40,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82
41,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64
42,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28

In [151]:
#check nulls
df.isnull().any()
#nan is not shown it only shows real null so better using unique data

Player                 False
Span                   False
Mat                    False
Inns                   False
Not_Outs               False
Runs                   False
Highest_Inns_score     False
Ave                    False
Ball_face               True
Batting_strike_rate     True
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

In [152]:
df[df['Ball_face'].isna()==1]

,Player,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s
10,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,NaN,NaN,15,19,6,258+,2
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,NaN,NaN,15,14,1,107+,11

In [182]:
df[df['Batting_strike_rate'].isna()==1]

Empty DataFrame
Columns: [Country, Span, Mat, Inns, Not_Outs, Runs, Highest_Inns_score, Ave, Ball_face, Batting_strike_rate, 100, 50, 0, 4s, 6s, Rookie_Year, Final_Year, Player_name]
Index: []

In [154]:
df['Ball_face']=df['Ball_face'].fillna(0)

In [183]:
df['Batting_strike_rate']=df['Batting_strike_rate'].fillna(0)

In [184]:
df.head(50)

,Country,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Player_name
0,AUS,1928-1948,52,80,10,6996,<NA>,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,DG Bradman
1,SL,2022-2025,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,PHKD Mendis
2,AUS,2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges
3,SA,1963-1970,23,41,4,2256,<NA>,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock
4,SA,1963-1970,23,41,4,2256,<NA>,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock
5,WI,1930-1954,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104+,1,1930,1954,GA Headley
6,ENG,1924-1935,54,84,9,4555,<NA>,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,H Sutcliffe
7,ENG,1931-1939,20,31,5,1540,<NA>,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,E Paynter
8,ENG,1955-1968,82,131,15,6806,<NA>,58.67,4957+,42.42,20,35,5,591+,27,1955,1968,KF Barrington
9,SL,2000-2015,134,233,17,12400,<NA>,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara
10,WI,1948-1958,48,81,5,4455,<NA>,58.61,0,0.00,15,19,6,258+,2,1948,1958,ED Weekes
11,ENG,1927-1947,85,140,16,7249,336,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,WR Hammond
12,WI,1954-1974,93,160,21,8032,365,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,GS Sobers
13,SL,2000-2015,134,233,17,12400,<NA>,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara
14,ENG,1908-1930,61,102,7,5410,<NA>,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,JB Hobbs
15,WI,1948-1960,44,74,7,3798,<NA>,56.68,0,0.00,15,14,1,107+,11,1948,1960,CL Walcott
16,ENG,1937-1955,79,138,15,6971,<NA>,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,L Hutton
17,AUS,2010-2026,123,220,28,10763,<NA>,56.05,19966,53.90,37,44,11,1172,67,2010,2026,SPD Smith
18,ICC/SA,1995-2013,166,280,40,13289,<NA>,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis
19,ENG,1921-1929,14,20,2,990,<NA>,55.00,178+,29.21,3,6,2,37+,2,1921,1929,GE Tyldesley
20,ENG,2022-2026,35,60,2,3178,<NA>,54.79,3660,86.83,10,15,4,339,52,2022,2026,HC Brook
21,NZ,2010-2025,108,192,19,9461,<NA>,54.68,18198,51.98,33,38,11,1056,28,2010,2025,KS Williamson
22,WI,1968-1973,15,29,5,1301,<NA>,54.20,665+,35.48,4,4,1,65+,1,1968,1973,CA Davis
23,IND,1993-1995,17,21,1,1084,<NA>,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli
24,AUS,1970-1984,87,151,19,7110,247,53.86,13079+,51.53,24,31,12,755,16,1970,1984,GS Chappell
25,SA,1935-1951,34,62,7,2960,<NA>,53.81,108+,63.88,9,14,3,115+,6,1935,1951,AD Nourse
26,IND,1989-2013,200,329,33,15921,248,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,SR Tendulkar
27,ICC/WI,1990-2006,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara
28,PAK,1976-1993,124,189,21,8832,280,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,Javed Miandad
29,ICC/IND,1996-2012,164,286,32,13288,<NA>,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid
30,PAK,1998-2010,90,156,12,7530,<NA>,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf
31,PAK,2000-2017,118,213,19,10099,<NA>,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan
32,AUS,1995-2012,168,287,29,13378,<NA>,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting
33,AUS,1920-1929,20,32,5,1394,201,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,J Ryder
34,ZIM,1992-2002,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower
35,AUS,2005-2013,79,137,16,6235,<NA>,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey
36,WI,1994-2015,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul
37,IND,1971-1987,125,214,16,10122,236,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,SM Gavaskar
38,ENG,2012-2026,163,298,25,13943,<NA>,51.07,24242,57.51,41,66,15,1492,46,2012,2026,JE Root
39,AUS,1985-2004,168,260,46,10927,<NA>,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh
40,AUS,1994-2009,103,184,14,8625,<NA>,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden
41,SA,2004-2018,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers
42,AUS,1978-1994,156,265,44,11174,<NA>,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AR Border

In [185]:
#drop dublicate
df.duplicated()

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
dtype: bool

In [186]:
#remove dublicate  check
df[df['Player'].duplicated()==1]

KeyError: 'Player'

In [187]:
df.drop_duplicates()

,Country,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Player_name
0,AUS,1928-1948,52,80,10,6996,<NA>,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,DG Bradman
1,SL,2022-2025,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,PHKD Mendis
2,AUS,2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges
3,SA,1963-1970,23,41,4,2256,<NA>,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock
5,WI,1930-1954,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104+,1,1930,1954,GA Headley
6,ENG,1924-1935,54,84,9,4555,<NA>,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,H Sutcliffe
7,ENG,1931-1939,20,31,5,1540,<NA>,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,E Paynter
8,ENG,1955-1968,82,131,15,6806,<NA>,58.67,4957+,42.42,20,35,5,591+,27,1955,1968,KF Barrington
9,SL,2000-2015,134,233,17,12400,<NA>,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara
10,WI,1948-1958,48,81,5,4455,<NA>,58.61,0,0.00,15,19,6,258+,2,1948,1958,ED Weekes
11,ENG,1927-1947,85,140,16,7249,336,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,WR Hammond
12,WI,1954-1974,93,160,21,8032,365,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,GS Sobers
14,ENG,1908-1930,61,102,7,5410,<NA>,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,JB Hobbs
15,WI,1948-1960,44,74,7,3798,<NA>,56.68,0,0.00,15,14,1,107+,11,1948,1960,CL Walcott
16,ENG,1937-1955,79,138,15,6971,<NA>,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,L Hutton
17,AUS,2010-2026,123,220,28,10763,<NA>,56.05,19966,53.90,37,44,11,1172,67,2010,2026,SPD Smith
18,ICC/SA,1995-2013,166,280,40,13289,<NA>,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis
19,ENG,1921-1929,14,20,2,990,<NA>,55.00,178+,29.21,3,6,2,37+,2,1921,1929,GE Tyldesley
20,ENG,2022-2026,35,60,2,3178,<NA>,54.79,3660,86.83,10,15,4,339,52,2022,2026,HC Brook
21,NZ,2010-2025,108,192,19,9461,<NA>,54.68,18198,51.98,33,38,11,1056,28,2010,2025,KS Williamson
22,WI,1968-1973,15,29,5,1301,<NA>,54.20,665+,35.48,4,4,1,65+,1,1968,1973,CA Davis
23,IND,1993-1995,17,21,1,1084,<NA>,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli
24,AUS,1970-1984,87,151,19,7110,247,53.86,13079+,51.53,24,31,12,755,16,1970,1984,GS Chappell
25,SA,1935-1951,34,62,7,2960,<NA>,53.81,108+,63.88,9,14,3,115+,6,1935,1951,AD Nourse
26,IND,1989-2013,200,329,33,15921,248,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,SR Tendulkar
27,ICC/WI,1990-2006,131,232,6,11953,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara
28,PAK,1976-1993,124,189,21,8832,280,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,Javed Miandad
29,ICC/IND,1996-2012,164,286,32,13288,<NA>,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid
30,PAK,1998-2010,90,156,12,7530,<NA>,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf
31,PAK,2000-2017,118,213,19,10099,<NA>,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan
32,AUS,1995-2012,168,287,29,13378,<NA>,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting
33,AUS,1920-1929,20,32,5,1394,201,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,J Ryder
34,ZIM,1992-2002,63,112,19,4794,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower
35,AUS,2005-2013,79,137,16,6235,<NA>,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey
36,WI,1994-2015,164,280,49,11867,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul
37,IND,1971-1987,125,214,16,10122,236,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,SM Gavaskar
38,ENG,2012-2026,163,298,25,13943,<NA>,51.07,24242,57.51,41,66,15,1492,46,2012,2026,JE Root
39,AUS,1985-2004,168,260,46,10927,<NA>,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh
40,AUS,1994-2009,103,184,14,8625,<NA>,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden
41,SA,2004-2018,114,191,18,8765,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers
42,AUS,1978-1994,156,265,44,11174,<NA>,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AR Border

In [188]:
#start span into start and end date
df['Span'].str.split(pat='-')

0     [1928, 1948]
1     [2022, 2025]
2     [2015, 2016]
3     [1963, 1970]
4     [1963, 1970]
5     [1930, 1954]
6     [1924, 1935]
7     [1931, 1939]
8     [1955, 1968]
9     [2000, 2015]
10    [1948, 1958]
11    [1927, 1947]
12    [1954, 1974]
13    [2000, 2015]
14    [1908, 1930]
15    [1948, 1960]
16    [1937, 1955]
17    [2010, 2026]
18    [1995, 2013]
19    [1921, 1929]
20    [2022, 2026]
21    [2010, 2025]
22    [1968, 1973]
23    [1993, 1995]
24    [1970, 1984]
25    [1935, 1951]
26    [1989, 2013]
27    [1990, 2006]
28    [1976, 1993]
29    [1996, 2012]
30    [1998, 2010]
31    [2000, 2017]
32    [1995, 2012]
33    [1920, 1929]
34    [1992, 2002]
35    [2005, 2013]
36    [1994, 2015]
37    [1971, 1987]
38    [2012, 2026]
39    [1985, 2004]
40    [1994, 2009]
41    [2004, 2018]
42    [1978, 1994]
Name: Span, dtype: object

In [189]:
df['Span'].str.split(pat='-').str[0]

0     1928
1     2022
2     2015
3     1963
4     1963
5     1930
6     1924
7     1931
8     1955
9     2000
10    1948
11    1927
12    1954
13    2000
14    1908
15    1948
16    1937
17    2010
18    1995
19    1921
20    2022
21    2010
22    1968
23    1993
24    1970
25    1935
26    1989
27    1990
28    1976
29    1996
30    1998
31    2000
32    1995
33    1920
34    1992
35    2005
36    1994
37    1971
38    2012
39    1985
40    1994
41    2004
42    1978
Name: Span, dtype: object

In [190]:
df['Rookie_Year']=df['Span'].str.split(pat='-').str[0]
df['Final_Year']=df['Span'].str.split(pat='-').str[1]

In [191]:
df['Player'].str.split(pat='(')

KeyError: 'Player'

In [164]:
df['Country']=df['Player'].str.split(pat='(').str[1]
df.head()

,Player,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS)
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL)
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS)
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA)
4,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA)

In [165]:
df['Country']=df['Player'].str.split(pat='(').str[1]
df.head()

,Player,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS)
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL)
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS)
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA)
4,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA)

In [166]:
df['Player_name']=df['Player'].str.split(pat='(').str[0]
df

,Player,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country,Player_name
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS),DG Bradman
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL),PHKD Mendis
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS),AC Voges
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA),RG Pollock
4,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA),RG Pollock
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI),GA Headley
6,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG),H Sutcliffe
7,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,ENG),E Paynter
8,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968,ENG),KF Barrington
9,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL),KC Sangakkara
10,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958,WI),ED Weekes
11,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,ENG),WR Hammond
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,WI),GS Sobers
13,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL),KC Sangakkara
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,ENG),JB Hobbs
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11,1948,1960,WI),CL Walcott
16,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,ENG),L Hutton
17,SPD Smith (AUS),2010-2026,123,220,28,10763,239,56.05,19966,53.90,37,44,11,1172,67,2010,2026,AUS),SPD Smith
18,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA),JH Kallis
19,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929,ENG),GE Tyldesley
20,HC Brook (ENG),2022-2026,35,60,2,3178,317,54.79,3660,86.83,10,15,4,339,52,2022,2026,ENG),HC Brook
21,KS Williamson (NZ),2010-2025,108,192,19,9461,251,54.68,18198,51.98,33,38,11,1056,28,2010,2025,NZ),KS Williamson
22,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973,WI),CA Davis
23,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND),VG Kambli
24,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984,AUS),GS Chappell
25,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951,SA),AD Nourse
26,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,IND),SR Tendulkar
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI),BC Lara
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,PAK),Javed Miandad
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND),R Dravid
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK),Mohammad Yousuf
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK),Younis Khan
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS),RT Ponting
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,AUS),J Ryder
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM),A Flower
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS),MEK Hussey
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI),S Chanderpaul
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,IND),SM Gavaskar
38,JE Root (ENG),2012-2026,163,298,25,13943,262,51.07,24242,57.51,41,66,15,1492,46,2012,2026,ENG),JE Root
39,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS),SR Waugh
40,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS),ML Hayden
41,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA),AB de Villiers
42,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AUS),AR Border

In [167]:
#remove rightstrip
df['Country'] = df['Country'].str.rstrip(')')
df

,Player,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country,Player_name
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS,DG Bradman
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL,PHKD Mendis
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS,AC Voges
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA,RG Pollock
4,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA,RG Pollock
5,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI,GA Headley
6,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG,H Sutcliffe
7,E Paynter (ENG),1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,ENG,E Paynter
8,KF Barrington (ENG),1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968,ENG,KF Barrington
9,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL,KC Sangakkara
10,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958,WI,ED Weekes
11,WR Hammond (ENG),1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,ENG,WR Hammond
12,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,WI,GS Sobers
13,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL,KC Sangakkara
14,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,ENG,JB Hobbs
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11,1948,1960,WI,CL Walcott
16,L Hutton (ENG),1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,ENG,L Hutton
17,SPD Smith (AUS),2010-2026,123,220,28,10763,239,56.05,19966,53.90,37,44,11,1172,67,2010,2026,AUS,SPD Smith
18,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA,JH Kallis
19,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929,ENG,GE Tyldesley
20,HC Brook (ENG),2022-2026,35,60,2,3178,317,54.79,3660,86.83,10,15,4,339,52,2022,2026,ENG,HC Brook
21,KS Williamson (NZ),2010-2025,108,192,19,9461,251,54.68,18198,51.98,33,38,11,1056,28,2010,2025,NZ,KS Williamson
22,CA Davis (WI),1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973,WI,CA Davis
23,VG Kambli (IND),1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND,VG Kambli
24,GS Chappell (AUS),1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984,AUS,GS Chappell
25,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951,SA,AD Nourse
26,SR Tendulkar (IND),1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,IND,SR Tendulkar
27,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI,BC Lara
28,Javed Miandad (PAK),1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,PAK,Javed Miandad
29,R Dravid (ICC/IND),1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND,R Dravid
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK,Mohammad Yousuf
31,Younis Khan (PAK),2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK,Younis Khan
32,RT Ponting (AUS),1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS,RT Ponting
33,J Ryder (AUS),1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,AUS,J Ryder
34,A Flower (ZIM),1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM,A Flower
35,MEK Hussey (AUS),2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS,MEK Hussey
36,S Chanderpaul (WI),1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI,S Chanderpaul
37,SM Gavaskar (IND),1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,IND,SM Gavaskar
38,JE Root (ENG),2012-2026,163,298,25,13943,262,51.07,24242,57.51,41,66,15,1492,46,2012,2026,ENG,JE Root
39,SR Waugh (AUS),1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS,SR Waugh
40,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS,ML Hayden
41,AB de Villiers (SA),2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA,AB de Villiers
42,AR Border (AUS),1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AUS,AR Border

In [168]:
df = df.drop('Player', axis=1)
df

,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country,Player_name
0,1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS,DG Bradman
1,2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL,PHKD Mendis
2,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS,AC Voges
3,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA,RG Pollock
4,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA,RG Pollock
5,1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI,GA Headley
6,1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,ENG,H Sutcliffe
7,1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,ENG,E Paynter
8,1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968,ENG,KF Barrington
9,2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL,KC Sangakkara
10,1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958,WI,ED Weekes
11,1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,ENG,WR Hammond
12,1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,WI,GS Sobers
13,2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL,KC Sangakkara
14,1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,ENG,JB Hobbs
15,1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11,1948,1960,WI,CL Walcott
16,1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,ENG,L Hutton
17,2010-2026,123,220,28,10763,239,56.05,19966,53.90,37,44,11,1172,67,2010,2026,AUS,SPD Smith
18,1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA,JH Kallis
19,1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929,ENG,GE Tyldesley
20,2022-2026,35,60,2,3178,317,54.79,3660,86.83,10,15,4,339,52,2022,2026,ENG,HC Brook
21,2010-2025,108,192,19,9461,251,54.68,18198,51.98,33,38,11,1056,28,2010,2025,NZ,KS Williamson
22,1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973,WI,CA Davis
23,1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND,VG Kambli
24,1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984,AUS,GS Chappell
25,1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951,SA,AD Nourse
26,1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,IND,SR Tendulkar
27,1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI,BC Lara
28,1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,PAK,Javed Miandad
29,1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND,R Dravid
30,1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK,Mohammad Yousuf
31,2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK,Younis Khan
32,1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS,RT Ponting
33,1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,AUS,J Ryder
34,1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM,A Flower
35,2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS,MEK Hussey
36,1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI,S Chanderpaul
37,1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,IND,SM Gavaskar
38,2012-2026,163,298,25,13943,262,51.07,24242,57.51,41,66,15,1492,46,2012,2026,ENG,JE Root
39,1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS,SR Waugh
40,1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,AUS,ML Hayden
41,2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA,AB de Villiers
42,1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AUS,AR Border

In [169]:
# Example: move 'Country' column to first position
col = df.pop('Country')        # removes 'Country' and keeps the data
df.insert(0, 'Country', col)
df

,Country,Span,Mat,Inns,Not_Outs,Runs,Highest_Inns_score,Ave,Ball_face,Batting_strike_rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Player_name
0,AUS,1928-1948,52,80,10,6996,334,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,DG Bradman
1,SL,2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,PHKD Mendis
2,AUS,2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AC Voges
3,SA,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock
4,SA,1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,RG Pollock
5,WI,1930-1954,22,40,4,2190,270*,60.83,416+,56.00,10,5,2,104+,1,1930,1954,GA Headley
6,ENG,1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202+,6,1924,1935,H Sutcliffe
7,ENG,1931-1939,20,31,5,1540,243,59.23,1288+,45.88,4,7,3,125+,4,1931,1939,E Paynter
8,ENG,1955-1968,82,131,15,6806,256,58.67,4957+,42.42,20,35,5,591+,27,1955,1968,KF Barrington
9,SL,2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara
10,WI,1948-1958,48,81,5,4455,207,58.61,0,0.00,15,19,6,258+,2,1948,1958,ED Weekes
11,ENG,1927-1947,85,140,16,7249,336*,58.45,7491+,38.07,22,24,4,419+,27,1927,1947,WR Hammond
12,WI,1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+,1954,1974,GS Sobers
13,SL,2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,KC Sangakkara
14,ENG,1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8,1908,1930,JB Hobbs
15,WI,1948-1960,44,74,7,3798,220,56.68,0,0.00,15,14,1,107+,11,1948,1960,CL Walcott
16,ENG,1937-1955,79,138,15,6971,364,56.67,2844+,39.34,19,33,5,358+,7,1937,1955,L Hutton
17,AUS,2010-2026,123,220,28,10763,239,56.05,19966,53.90,37,44,11,1172,67,2010,2026,SPD Smith
18,ICC/SA,1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,JH Kallis
19,ENG,1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37+,2,1921,1929,GE Tyldesley
20,ENG,2022-2026,35,60,2,3178,317,54.79,3660,86.83,10,15,4,339,52,2022,2026,HC Brook
21,NZ,2010-2025,108,192,19,9461,251,54.68,18198,51.98,33,38,11,1056,28,2010,2025,KS Williamson
22,WI,1968-1973,15,29,5,1301,183,54.20,665+,35.48,4,4,1,65+,1,1968,1973,CA Davis
23,IND,1993-1995,17,21,1,1084,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,VG Kambli
24,AUS,1970-1984,87,151,19,7110,247*,53.86,13079+,51.53,24,31,12,755,16,1970,1984,GS Chappell
25,SA,1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115+,6,1935,1951,AD Nourse
26,IND,1989-2013,200,329,33,15921,248*,53.78,29437+,54.04,51,68,14,2058+,69,1989,2013,SR Tendulkar
27,ICC/WI,1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88,1990,2006,BC Lara
28,PAK,1976-1993,124,189,21,8832,280*,52.57,15164+,45.99,23,43,6,788+,48,1976,1993,Javed Miandad
29,ICC/IND,1996-2012,164,286,32,13288,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,R Dravid
30,PAK,1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,Mohammad Yousuf
31,PAK,2000-2017,118,213,19,10099,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,Younis Khan
32,AUS,1995-2012,168,287,29,13378,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,RT Ponting
33,AUS,1920-1929,20,32,5,1394,201*,51.62,2035+,44.86,3,9,1,102+,3,1920,1929,J Ryder
34,ZIM,1992-2002,63,112,19,4794,232*,51.54,10636,45.07,12,27,5,543,20,1992,2002,A Flower
35,AUS,2005-2013,79,137,16,6235,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,MEK Hussey
36,WI,1994-2015,164,280,49,11867,203*,51.37,27395,43.31,30,66,15,1285,36,1994,2015,S Chanderpaul
37,IND,1971-1987,125,214,16,10122,236*,51.12,14184+,43.35,34,45,12,908+,26,1971,1987,SM Gavaskar
38,ENG,2012-2026,163,298,25,13943,262,51.07,24242,57.51,41,66,15,1492,46,2012,2026,JE Root
39,AUS,1985-2004,168,260,46,10927,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,SR Waugh
40,AUS,1994-2009,103,184,14,8625,380,50.73,14349,60.10,30,29,14,1049,82,1994,2009,ML Hayden
41,SA,2004-2018,114,191,18,8765,278*,50.66,16077,54.51,22,46,8,1024,64,2004,2018,AB de Villiers
42,AUS,1978-1994,156,265,44,11174,205,50.56,27002+,41.09,27,63,11,1161,28,1978,1994,AR Border

In [171]:
df.dtypes

Country                 object
Span                    object
Mat                      int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_score      object
Ave                    float64
Ball_face               object
Batting_strike_rate    float64
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year             object
Final_Year              object
Player_name             object
dtype: object

In [203]:
df.isnull().any()

Country                False
Span                   False
Mat                    False
Inns                   False
Not_Outs               False
Runs                   False
Highest_Inns_score     False
Ave                    False
Ball_face              False
Batting_strike_rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
Rookie_Year            False
Final_Year             False
Player_name            False
dtype: bool

In [239]:
print(df['Highest_Inns_score'].head(10))
print(df['Highest_Inns_score'].isna().sum())

0    NaN
1    182
2    269
3    NaN
4    NaN
5    270
6    NaN
7    NaN
8    NaN
9    NaN
Name: Highest_Inns_score, dtype: object
29

In [240]:
df['Highest_Inns_score'] = df['Highest_Inns_score'].str.replace(r'\*', '', regex=True)